TASK-41619 : Synchronization AD - User status
Meeds-io/core pull request #21
Opened 2021-03-25 16:11 UTC by GouadriaHanen

added enabled to attributes while retrieving users from AD

2021-03-30 19:12 UTC, ahamdi requested changes

2021-03-30 19:12 UTC, ahamdi commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
>        internalUser = externalUser;
```suggestion
      organizationService.getUserHandler().createUser(externalUser, true);
      if (!externalUser.isEnabled()) {
        organizationService.getUserHandler().setEnabled(externalUser.getUserName(), false, true);
      }
      internalUser = externalUser;
```

2021-03-31 16:07 UTC, GouadriaHanen commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
>        internalUser = externalUser;
while  creating a disabled user it throws a disabled user exception 
so we need to enable it, create it then disabled it

2021-04-07 10:44 UTC, ahamdi commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
>        internalUser = externalUser;
Ok please add a comment in the code to explain why we need to create the user enabled and then set him as disabled.

2021-04-13 08:35 UTC, GouadriaHanen commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
>        internalUser = externalUser;
done!

2021-04-16 11:12 UTC, ahamdi submitted a review, later dismissed

2021-04-16 15:03 UTC, ahamdi approved these changes

2021-04-16 15:13 UTC, merged