Fix : Update Profile when synchronized profile property setting from AD - EXO-65023 - Meeds-io/meeds#1084
Meeds-io/core pull request #85
Opened 2023-09-01 20:43 UTC by sofyenne

2023-09-06 10:37 UTC, ahamdi requested changes
COuld you add a UT for this change too ?

2023-09-06 10:37 UTC, ahamdi commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
> -    if (externalUserProfile != null && externalUserProfile.getUserInfoMap() != null
Why do you remove the logic of comparing external and internal user profile that checks if there are modification ?

2023-09-06 10:37 UTC, ahamdi commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
> +    listenerService.broadcast(IDMExternalStoreService.USER_PROFILE_ADDED_FROM_EXTERNAL_STORE, this, userInfoMap);
IMO this should not be fired unles there is a modification

2023-09-06 10:37 UTC, ahamdi commented on exo.core.component.organization.api/src/main/java/org/exoplatform/services/organization/externalstore/IDMExternalStoreImportService.java
> +    return null;
If this function does not have top return a value, we change the signature, otherwise we return the user profile as it was done

2023-09-07 11:52 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-07 14:08 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-07 16:07 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-07 20:26 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-08 15:43 UTC, ahamdi approved these changes

2023-09-08 15:43 UTC, merged